### PR TITLE
build for npm

### PR DESCRIPTION
**Pull request by rixrix**
@the-real-blackh here's another set of changes

what's inside:

- npm commands for building ts file to js `npm run build` , and running tests `npm run test` 
- moved sodium *.ts files in `./src/lib` and test files in `./src/test`
- added compiled js in `./dist` folder
- renamed package name from `sodium` to `sodium-frp` - there's an existing npm library called `sodium`

a few things though before we publish to npm registry:

- we might need to add a simple example that we can stick in `./example/index.html` , I'll play around with the library over the next few days but if you have something usable that might help me finetune the build process instead
- update README on how to use sodium
- we might need to rename the library to something like `sodiumjs` or `sodiumfrpjs` or other - easier for people to recognise that this is part of sodium frp library

thoughts ?

Thanks
-R

### CODE REVIEW

**Comment by the-real-blackh** [comment]
Thank you! I need to add one more API method. I'll go through your list and see what I can do.

I will also work on an example, perhaps one of the book examples.

**Comment by rixrix** [comment]
cheers!

I'll sort out other stuff - prolly more testing with the library. thanks

**Comment by the-real-blackh** [comment]
The API method I want to add is IOAction.fromAsync() which will allow you to represent asynchronous I/O (such as an XMLHttpRequest) as a function from Stream<A> to Stream<B>. The current API doesn't quite allow for that, because in Javascript we don't have addCleanup().

**Comment by rixrix** [comment]
if you have an existing sodium implementation from eg. Java/C++  then we might be able to port that in Js (granting it is doable) or grab an existing JS library that we could use as dependency - if you could put create a ticket with details on it that'd be helpful

**Comment by the-real-blackh** [comment]
Don't worry - it's easy - I'll do it.

**Comment by rixrix** [comment]
@the-real-blackh I managed to make the `suite.ts` execute in the browser rather than from the cli via node but I had to go through a bunch of hops to make it work - a few modifications etc:

We might need to restructure the *.ts files a little bit so it's easy for us to build our library in amd, commonjs, es6, or umd formats.

a work-in-progress is on my branch https://github.com/rixrix/sodium-typescript/tree/umd-library
- it uses webpack for transpiling *.ts files and bundling it to *.js in umd format
- there's a super basic example from your `suite.ts` under `examples/basic` folder

**Comment by the-real-blackh** [comment]
Thank you - It would have taken me a long long time to do what you've done. You'll see that I added the IOAction.fromAsync() API to the project and renamed some files from sodium to sodium-frp. Please just re-arrange things as you think they should be. Nothing depends on the current structure.

Once you have got that stuff worked out, I'll work on a demo. I don't understand all the details of how JS modules are handled.

**Comment by rixrix** [comment]
great! I'll grab the latest changes then. I'll drop a PR once I've got the basics sorted out - thanks

**Comment by the-real-blackh** [comment]
You should have write access to the repo now.

**Comment by rixrix** [comment]
ha! I kept forgetting the write access, I'll give you a heads up then once it's in. cheers

**Pull request merged**
