### PR TITLE
High order dependency tracking

### PR DESCRIPTION
**Pull request by clinuxrulz**
concerns: #42 

does just that: https://github.com/SodiumFRP/sodium-typescript/issues/42#issuecomment-340291075
it allows us to provide that function for sodium to see all the sodium objects held in a value of a sodium object.

current solution: The following method gets added to cell:
```
    /**
     * High order depenency tracing. If any newly created sodium objects within a value of a cell of a sodium object
     * happen to accumulate state, this method will keep the accumulation of state up to date.
     */
    trace(extractor: (a: A) => (Stream<any> | Cell<any>)[]): Cell<A>;
```

This is more for review as it is adding a new feature to the library to solve a problem, and there might be more than one solution.

### CODE REVIEW

**Comment by clinuxrulz** [comment]
Do not merge this just yet. I ran a few tests, and this method is not working. I may have to mod it to manually listen/unlisten to each of the contained sodium objects.

**Comment by clinuxrulz** [comment]
Its ```Cell::liftArray(...)```, it needs to track its dependencies, I'll provide a fix later when I get home.

**Comment by clinuxrulz** [comment]
OK, ```Cell::trace()``` is tested/fixed now.

**Comment by clinuxrulz** [comment]
It's weird. I did not think ```.map(lambda1(x => x, ca))``` would of been required in ```Cell::liftArray``` in order for ```Cell::trace``` to work. It sort of suggests there is are some cells not getting tracked in switchC. I'll have to write some tests later.

**Comment by clinuxrulz** [comment]
Just a quick skim over the code. I can not see anything to cause a rank resort in ```switchC```, like there is in the Java version.

**Comment by the-real-blackh** [comment]
That does not sound right.

**Comment by clinuxrulz** [comment]
disregard my last comment. It looks the same as Java's ```switchC``` . I must of been thinking of a different method

**Comment by clinuxrulz** [comment]
I couldn't prove that ```.map(lambda1(x => x, ca))``` is required in ```Cell::liftArray```. seems to work fine without it when I tried out some tests. Could just be something I've done wrong in my larger code base.

**Comment by clinuxrulz** [comment]
Yep. ```.map(lambda1(x => x, ca))``` can go away, it was just something silly I've done on my end. I've been using Cell::trace for some time now and it feels like a must have. It even solves the issue of sending sodium objects through sink. We should have a vote sooner or later for weither this should be included.

**Pull request merged**
