### PR TITLE
added Cell::calm and Cell::calmEqRef

### PR DESCRIPTION
**Pull request by clinuxrulz**
regards #78

### CODE REVIEW

**Comment by clinuxrulz** [comment]
I actually hit a case at work where the non-lazy implementation of Cell::calm worked, and the lazy version failed. (the lazy version fell 1 step behind).

Is there any reason they should be different lazy/non-lazy in the case of Cell::calm? Or is it just something silly I've done on my end?

**Comment by the-real-blackh** [comment]
No - the result should be the same. If not, it would be a bug. The implementation has to be lazy, because otherwise it can't be used with cell/stream loops.

**Comment by clinuxrulz** [comment]
The Lazy returned by sampleLazy() is not memoized (i believe), and I'm calling it twice which does not help either. That is to say holdLazy and collectLazy can both see a different initial value due to no memoization.

**Comment by jam40jeff** [comment]
It could be related to this:

https://github.com/SodiumFRP/sodium/issues/122

**Comment by clinuxrulz** [comment]
As a additional safety measure. Multiple calls to sampleLazy() within the same transaction should return a reference to the same instance of Lazy.

**Comment by clinuxrulz** [comment]
@jam40jeff your correct with how holdLazy should work in your link. It is the same bug happening in the typescript version.

**Comment by jam40jeff** [comment]
I don't know the details of the TypeScript implementation, but what you described sounds exactly like what my fix for #122 (memoize the lazy at the end of the transaction in which it was created.)

**Comment by clinuxrulz** [comment]
I was wrong LazySample class does the memoization for Lazy from sampleLazy. I just failed to spot it.

**Comment by clinuxrulz** [comment]
That said. sample() and sampleLazy() can return different values.

sample() returns the value of the cell right now.

sampleLazy() returns the value of the cell at the end of transaction. Which could be different if the value of that cell is due to change in that transaction.

**Comment by the-real-blackh** [comment]
@clinuxrulz That would be a bug! sampleLazy() should be semantically the same as sample().

sampleLazy() should return the value before any changes queued up in the transaction (just like sample() does), but if it is a cell loop, it should resolve properly.

If you could raise this as a bug, that'd be great. If you want me to do it, then please just let me know everything you know about it.

**Comment by clinuxrulz** [comment]
Will need to do a test case 1st to demonstrate that it is semantically different. If I get time this weekend I'll give it a go.

**Comment by jam40jeff** [comment]
@clinuxrulz I'm a little skeptical that `sampleLazy()` is behaving as you describe as I'm pretty certain most operators would not pass the denotational semantics tests if that were the case.

**Comment by clinuxrulz** [comment]
@jam40jeff I have a feeling it is because the Lazy is not unboxed immediately by the other combinators, it is only unboxed when the resulting combinators value is unboxed. (A long chain of lazies). The semantics tests currently do not deal with forcibly unboxing lazy values early.

I could be wrong, but I'll see what I can find over the weekend.

**Comment by clinuxrulz** [comment]
@jam40jeff / @the-real-blackh , I was unable to make a failing test for sampleLazy(). It seems it is working correctly. I must of misjudged the behaviour of the code when I first read it.

**Comment by jam40jeff** [comment]
Thanks for looking into it.

**Pull request merged**
