### PR TITLE
reduced how often collect cycles is called

### PR DESCRIPTION
**Pull request by clinuxrulz**
regards #77

### CODE REVIEW

**Comment by clinuxrulz** [comment]
Note: jest is only working on an older version of node at the moment.
https://github.com/facebook/jest/issues/8069

So you can ignore the jest errors, all tests pass here.

**Comment by clinuxrulz** [comment]
Hold off merging this one. Problem still not resolved.

**Comment by clinuxrulz** [comment]
This PR is all good. I did some further investigation and it was calling collectCycles just once per transaction at most (less than once per transaction if no decrements occur). It was just the nature of the code I've written for that incremental update of three.js code, there are transactions occurring in that code when wiring up independent parts to the actual scene giving the illusion of many collectCycles in one transaction, when in fact it was one collectCycles in each of many transactions.

**Comment by the-real-blackh** [comment]
Are you missing some commit privileges?

**Comment by clinuxrulz** [comment]
No. I just like having a 2nd set of eyes to review what I do, just in case I make a mistake.

**Comment by clinuxrulz** [comment]
In the Travis log file I can see:
"Skipping a deployment with the npm provider because this is not a tagged commit"

Does that mean someone here has done CI? And we just need to tag the commit in order to get a new version on npm?

**Pull request merged**
