### PR TITLE
Coalesceless, fix #102

### LINKED ISSUE #102: Overworked Cell::lift(s)
This might be a known issue:
```
  let lines = [
    "Work it harder",
    "Make it better",
    "Do it faster",
    "Makes us stronger"
  ];
  let idx = 0;
  let c1 = new CellSink(0);
  let c2 = new CellSink(0);
  let c3 = new CellSink(0);
  let c4 = new CellSink(0);
  let c = c1.lift4(c2, c3, c4, (x1, x2, x3, x4) => {
    console.log(lines[idx]);
    idx = (idx + 1) % lines.length;
    return x1 + x2 + x3 + x4;
  });
  let kill = c.listen(() => {});
  Transaction.run(() => {
    c1.send(1);
    c2.send(2);
    c3.send(3);
    c4.send(4);
  });
  kill();
```

Outputs to console:
```
Work it harder
Make it better
Do it faster
```

Meaning  the lambda passed to ```Cell::lift4``` is being triggered 3 times here, and passing a value forwards one per transaction when the value changes which is fine. However I think we can make it better and only trigger the lambda passed to ```Cell::lift4``` twice in the example above.

### PR DESCRIPTION
**Pull request by clinuxrulz**
Regards: #102

### CODE REVIEW

**Comment by clinuxrulz** [comment]
Don't merge this yet! I do not think the solution for switchC is correct, even though all tests are passing. Will need to double check it.

**Comment by clinuxrulz** [comment]
coalesce-free ```switchC``` all good now. I found a missing pump() when debugging by doing random sort of same rank entries and insuring all tests pass with the random sorts. This can be merged now if your happy with it.

**Comment by the-real-blackh** [comment]
Please just go ahead. This is your project now.

By the way, I have done some performance work on sodium-cxx, because the project I use it for is demanding that. I may do some more. I am not using switch much because we don't have any proper memory management in the C++ version (even though I am using it in a production system - I just avoid switches where I don't need them).

**Comment by clinuxrulz** [comment]
One thing I had on my mind was the priority queue can just be an vector of hashmaps where each index into vector represents the _rank_, and the hashmap holds the _entries_ of the same rank about to be fired. When ever a rank changes for a vertex, its entry can efficiently be removed/readded (**O(1)**) into the priority queue without a resort. Also the minimum rank (minimum index) of the priority queue gets maintained for the start of the close of the transaction. Then a for-loop traverses this vector of treemaps to perform all the updates which should theoritically be done in **O(n)** for **n** _entries_ on the priority queue. The probably I run into is over-use of hashmaps happens to fragment the memory in a bad way causing GC performance issues.

**Comment by the-real-blackh** [comment]
Once the ranks are determined, the order of processing is fixed. There's no need to use a priority queue at runtime. Just capture the order somehow. Just haven't figured that out yet. This fixed order needs to be changed whenever a rank changes, of course.

**Comment by clinuxrulz** [comment]
OK. Hear me out:
 - Forget the existence of ```StreamWithSend```
 - Each vertex in the graph is responsible for updating its own state, and can see dependency vertices' states through lambda capture.
 - When a vertex is added to the graph it follows its own dependencies all the way back to the cellsink/streamsink vertex and adds itself to a decendents list.
 - When cellsink/streamsink vertices get fired during a transaction all their decendents get marked dirty. The dirty node are visited in any order during that transaction, and all of their dirty dependency get processed recursively removing their own dirty flag (marking clean) when updated.

Using the method above we can remove the priority queue. The switchC/switchS will need some care taken when updating the decendents at runtime in the cellsink/streamsink vertices.

**Comment by clinuxrulz** [comment]
Actually what I've described above could hurt the performance of Router (1000 marked dirty, but only 1 due to fire).

**Comment by clinuxrulz** [comment]
Suppose multiple decendents list. Like a high priority list and a low priority list. To give ```Stream.filter```, ```switchC```, ```switchS``` and router a chance to mark all dirty vertices before the currently dirty list gets overprocessed.

**Comment by clinuxrulz** [comment]
I know once the ranks are known the order is fixed. However not all vertices in that fixed order are required to be updated during that transaction, so the created expression would contain if-statements skipping some nodes. I'd argue that the dirty flags act as this if-statements in the expression, and that the descendants list from the sink vertices is an encoding of a fixed expression.

**Comment by clinuxrulz** [comment]
I'll trial some ideas in a separate repo to see what works. Would be really nice to execute fixed functions in sink vertices if possible.

**Pull request merged**
